mod descending_order;
mod leap_years;
mod complementary_dna;
mod tribonacci;
mod wilson_prime;
mod create_phone_number;
mod playing_with_digits;
mod century_from_year;
mod two_to_one;
mod array_diff;
mod range_extraction;
mod bit_counting;
mod good_vs_evil;
mod valid_braces;
mod simple_substitution_cipher_helper;
//mod point_in_polygon;
mod sum_of_odd_numbers;
mod power_of_two;
mod numbers_to_letters;
mod reversed_strings;
mod vowel_count;
mod multiples_of_3_or_5;
mod drying_potatoes;
mod buying_a_car;
mod remove_first_and_last_character;
mod decode_the_morse_code_advanced;

fn main() {
    descending_order::verify();
    leap_years::verify();
    complementary_dna::verify();
    tribonacci::verify();
    wilson_prime::verify();
    create_phone_number::verify();
    playing_with_digits::verify();
    century_from_year::verify();
    two_to_one::verify();
    array_diff::verify();
    range_extraction::verify();
    bit_counting::verify();
    good_vs_evil::verify();
    valid_braces::verify();
    simple_substitution_cipher_helper::verify();
//    point_in_polygon::verify();
    sum_of_odd_numbers::verify();
    power_of_two::verify();
    numbers_to_letters::verify();
    reversed_strings::verify();
    vowel_count::verify();
    multiples_of_3_or_5::verify();
    drying_potatoes::verify();
    buying_a_car::verify();
    remove_first_and_last_character::verify();
    decode_the_morse_code_advanced::verify();
}
